#############################################################################
# Makefile for building: Graph5
# Generated by qmake (2.01a) (Qt 4.6.0) on: ?r. sty 20 18:36:47 2010
# Project:  Graph5.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Graph5.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		picture.cpp \
		triangle.cpp \
		triangle2d.cpp \
		rgb.cpp moc_widget.cpp \
		moc_picture.cpp \
		moc_triangle.cpp \
		moc_triangle2d.cpp
OBJECTS       = main.o \
		widget.o \
		picture.o \
		triangle.o \
		triangle2d.o \
		rgb.o \
		moc_widget.o \
		moc_picture.o \
		moc_triangle.o \
		moc_triangle2d.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Graph5.pro
QMAKE_TARGET  = Graph5
DESTDIR       = 
TARGET        = Graph5

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Graph5.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Graph5.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Graph5.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Graph51.0.0 || $(MKDIR) .tmp/Graph51.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Graph51.0.0/ && $(COPY_FILE) --parents widget.h picture.h triangle.h triangle2d.h rgb.h .tmp/Graph51.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp picture.cpp triangle.cpp triangle2d.cpp rgb.cpp .tmp/Graph51.0.0/ && $(COPY_FILE) --parents widget.ui .tmp/Graph51.0.0/ && (cd `dirname .tmp/Graph51.0.0` && $(TAR) Graph51.0.0.tar Graph51.0.0 && $(COMPRESS) Graph51.0.0.tar) && $(MOVE) `dirname .tmp/Graph51.0.0`/Graph51.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Graph51.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_picture.cpp moc_triangle.cpp moc_triangle2d.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_picture.cpp moc_triangle.cpp moc_triangle2d.cpp
moc_widget.cpp: picture.h \
		triangle.h \
		triangle2d.h \
		rgb.h \
		widget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_picture.cpp: triangle.h \
		triangle2d.h \
		rgb.h \
		picture.h
	/usr/bin/moc $(DEFINES) $(INCPATH) picture.h -o moc_picture.cpp

moc_triangle.cpp: triangle.h
	/usr/bin/moc $(DEFINES) $(INCPATH) triangle.h -o moc_triangle.cpp

moc_triangle2d.cpp: rgb.h \
		triangle2d.h
	/usr/bin/moc $(DEFINES) $(INCPATH) triangle2d.h -o moc_triangle2d.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/usr/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h \
		picture.h \
		triangle.h \
		triangle2d.h \
		rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		picture.h \
		triangle.h \
		triangle2d.h \
		rgb.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

picture.o: picture.cpp picture.h \
		triangle.h \
		triangle2d.h \
		rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o picture.o picture.cpp

triangle.o: triangle.cpp triangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangle.o triangle.cpp

triangle2d.o: triangle2d.cpp triangle2d.h \
		rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangle2d.o triangle2d.cpp

rgb.o: rgb.cpp rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rgb.o rgb.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_picture.o: moc_picture.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_picture.o moc_picture.cpp

moc_triangle.o: moc_triangle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_triangle.o moc_triangle.cpp

moc_triangle2d.o: moc_triangle2d.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_triangle2d.o moc_triangle2d.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

